services:
  config.database:
    synthetic: true
  logger.connection:
    synthetic: true
    tags:
      - {name: 'logger', channel: 'connection'}
  connection.factory:
    class: Vainyl\Connection\Factory\ConnectionFactory
  connection.factory.logger:
    decorates: connection.factory
    class: Vainyl\Connection\Factory\Decorator\LoggerConnectionFactoryDecorator
    arguments: ['@connection.factory.logger.inner', '@logger.connection']
  connection.storage:
    class: Vainyl\Connection\Storage\ConnectionStorage
    arguments: ['@storage.prototype', '@connection.factory']