services:
  connection.factory:
    class: Vainyl\Connection\Factory\ConnectionFactory
  connection.factory.logger:
    decorates: connection.factory
    class: Vainyl\Connection\Decorator\LoggerConnectionDecorator
    arguments: ['@connection.factory.logger.inner', '@logger']
  connection.storage:
    parent: storage.proxy
    class: Vainyl\Connection\Storage\ConnectionStorage
    arguments: ['@connection.factory']