services:
  connection.factory:
    class: Vainyl\Connection\Factory\ConnectionFactory
  connection.factory.logger:
    decorates: connection.factory
    class: Vainyl\Connection\Decorator\LoggerConnectionDecorator
    arguments: ['@connection.factory.logger.inner', '@logger.connection']
  connection.storage:
    class: Vainyl\Connection\Storage\ConnectionStorage
    arguments: ['storage.prototype', '@connection.factory']