services:
  config.connection:
    synthetic: true
  logger.connection:
    synthetic: true
    tags:
      - {name: 'logger', channel: 'connection'}
  connection.decorator:
    class: Vainyl\Connection\Factory\ConnectionDecorator
  connection.decorator.logger:
    decorates: connection.decorator
    class: Vainyl\Connection\Factory\Decorator\LoggerConnectionDecoratorDecorator
    arguments: ['@connection.decorator.logger.inner', '@logger.connection']
  connection.storage:
    class: Vainyl\Connection\Storage\ConnectionStorage
    arguments: ['@storage.prototype']